---
kind: pipeline
name: linters
type: docker

steps:
  - name: tox
    image: fkrull/multi-python:bionic
    commands:
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -o /tmp/get-poetry.py
      - python3 /tmp/get-poetry.py
      - export PATH="$HOME/.poetry/bin:$PATH"
      - source $HOME/.poetry/env
      - pip install tox
      - tox -e py38 py39
trigger:
  branch:
    - develop

---
kind: pipeline
name: packaging
type: docker

steps:
  - name: tox -e packaging
    image: python:3.8-buster
    commands:
      - pip install tox==3.14.6
      - tox -e packaging

depends_on:
  - linters
trigger:
  event:
    - tags
