language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -o /tmp/get-poetry.py
  - python3 /tmp/get-poetry.py
  - export PATH="$HOME/.poetry/bin:$PATH"
  - pip install tox-travis

script: tox

after_success:
  - prospector -0
  - coveralls
